# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singup.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 477)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.done_botton = QtWidgets.QPushButton(self.centralwidget)
        self.done_botton.setGeometry(QtCore.QRect(240, 360, 131, 28))
        self.done_botton.setObjectName("done_botton")
        self.permissioncode_label = QtWidgets.QLabel(self.centralwidget)
        self.permissioncode_label.setGeometry(QtCore.QRect(410, 310, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.permissioncode_label.setFont(font)
        self.permissioncode_label.setObjectName("permissioncode_label")
        self.singusername_box = QtWidgets.QLineEdit(self.centralwidget)
        self.singusername_box.setGeometry(QtCore.QRect(200, 160, 191, 22))
        self.singusername_box.setObjectName("singusername_box")
        self.wrongpass_label = QtWidgets.QLabel(self.centralwidget)
        self.wrongpass_label.setGeometry(QtCore.QRect(190, 240, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.wrongpass_label.setFont(font)
        self.wrongpass_label.setAcceptDrops(False)
        self.wrongpass_label.setTextFormat(QtCore.Qt.AutoText)
        self.wrongpass_label.setObjectName("wrongpass_label")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(410, 160, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.singuserpassword_box = QtWidgets.QLineEdit(self.centralwidget)
        self.singuserpassword_box.setGeometry(QtCore.QRect(200, 200, 191, 22))
        self.singuserpassword_box.setObjectName("singuserpassword_box")
        self.permissioncode_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.permissioncode_checkbox.setGeometry(QtCore.QRect(240, 270, 131, 20))
        self.permissioncode_checkbox.setObjectName("permissioncode_checkbox")
        self.userpassword_label = QtWidgets.QLabel(self.centralwidget)
        self.userpassword_label.setGeometry(QtCore.QRect(410, 200, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.userpassword_label.setFont(font)
        self.userpassword_label.setObjectName("userpassword_label")
        self.permissioncode_box_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.permissioncode_box_2.setGeometry(QtCore.QRect(200, 310, 191, 22))
        self.permissioncode_box_2.setObjectName("permissioncode_box_2")
        self.wrongcode_label = QtWidgets.QLabel(self.centralwidget)
        self.wrongcode_label.setGeometry(QtCore.QRect(230, 340, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.wrongcode_label.setFont(font)
        self.wrongcode_label.setAcceptDrops(False)
        self.wrongcode_label.setTextFormat(QtCore.Qt.AutoText)
        self.wrongcode_label.setObjectName("wrongcode_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.done_botton.setText(_translate("MainWindow", "אישור"))
        self.permissioncode_label.setText(_translate("MainWindow", "קוד הרשאה"))
        self.wrongpass_label.setText(_translate("MainWindow", "השם משתמש או הסיסמא אינם תקינים"))
        self.username_label.setText(_translate("MainWindow", "שם משתמש"))
        self.label.setText(_translate("MainWindow", "הרשמה"))
        self.permissioncode_checkbox.setText(_translate("MainWindow", "הרשאות מיוחדות"))
        self.userpassword_label.setText(_translate("MainWindow", "סיסמא"))
        self.wrongcode_label.setText(_translate("MainWindow", "קוד ההרשאה אינו תקין"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
